<?php
namespace App\Http\Controllers;

use App\Parsedown;
use Illuminate\Http\Request;
use App\Http\Requests;

class HomeController extends Controller{
    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(){
        $parsedown=new Parsedown();
        $a='# My article
 Welcome to my article,
* Point one
* Point two
* Point three
```
<?php
foreach(range(1,10) as $k){
echo $x;
}
?>
```
Here is some echo `\'inline code\'`;';
        $a=file_get_contents(public_path('jdy.txt'));
        $b= Parsedown::instance()->text($a);
        /*$c='<style> pre code{background-color: rgba(46, 79, 37, 0.6)}</style>';
        $b.=$c;*/
        return view('blog.index',['text'=>$b]);
        //echo $b;
        //var_dump("sdsdd");
    }
}