<?php
namespace App\Http\Controllers;

use App\Parsedown;
use Illuminate\Http\Request;
use App\Http\Requests;

class HomeController extends Controller
{
    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $a = '# My article
 Welcome to my article,
* Point one
* Point two
* Point three
```
<?php
foreach(range(1,10) as $k){
echo $x;
}
?>
```
Here is some echo `\'inline code\'`;';
        $fileContent = '';
        $time = 0;
        /*get directory of file*/
        $handle = fopen(public_path('jdy.txt'), 'r');

        /*add a anchor to each title and then use javascript to Automatically generate directory*/
        while (!feof($handle)) {
            $lineStr = fgets($handle);
            if (substr($lineStr, 0, 1) == '#') {

                if (substr($lineStr, 0, 4) == '####') {
                    /*this is h4*/
                    $anchor = '<p><a name=' . $time . '></a></p>';
                    $fileContent .= $anchor . "\n";
                    $fileContent .= $lineStr;
                    $time++;
                }
                if (substr($lineStr, 0, 3) == '###' && substr($lineStr, 0, 4) != '####') {
                    /*this is h3*/
                    $anchor = '<p><a name=' . $time . '></a></p>';
                    $fileContent .= $anchor . "\n";
                    $fileContent .= $lineStr;
                    $time++;
                }
                if (substr($lineStr, 0, 2) == '##' && substr($lineStr, 0, 3) != '###') {
                    /*this is h2*/
                    $anchor = '<p><a name=' . $time . '></a></p>';
                    $fileContent .= $anchor . "\n";
                    $fileContent .= $lineStr;
                    $time++;
                }
                if (substr($lineStr, 0, 1) == '#' && substr($lineStr, 0, 2) != '##') {
                    /*this is h1*/
                    $anchor = '<p><a name=' . $time . '></a></p>';
                    $fileContent .= $anchor . "\n";
                    $fileContent .= $lineStr;
                    $time++;
                }

            } else {
                $fileContent .= $lineStr;
            }

        }

        fclose($handle);
        $b = Parsedown::instance()->text($fileContent);

        return view('blog.index', ['text' => $b]);

    }

    public function modifyNodeName(Request $request){

    }

    public function adjustNodePlace(Request $request){

    }
    public function addNewNode(Request $request){

    }

    public function deleteNode(Request $request){

    }

}
